version: '3.8'

services:
  backend:
    build: ./backend
    container_name: agrifuture-backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend/agri.db:/app/agri.db
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: agrifuture-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

networks:
  default:
    name: agrifuture-network
