from fastapi import APIRouter, Depends
from fastapi.responses import FileResponse
from pydantic import BaseModel
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
import os
import uuid
from main import verify_token

router = APIRouter()

# =========================
# 📁 REPORT DIRECTORY
# =========================
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORT_DIR = os.path.join(BASE_DIR, "reports")
os.makedirs(REPORT_DIR, exist_ok=True)


# =========================
# 📦 REQUEST MODEL
# =========================
class ReportRequest(BaseModel):
    disease: str
    confidence: float
    advice: str
    medicine: str
    fertilizer: str = ""
    soil: str = ""
    root_health: str = ""
    language: str = "en"


# =========================
# 🌍 SIMPLE TRANSLATION LAYER
# =========================
def translate(text, lang):
    if not text:
        return ""

    if lang == "hi":
        return f"🇮🇳 हिंदी: {text}"
    elif lang == "mr":
        return f"🇮🇳 मराठी: {text}"
    return text


# =========================
# 📄 PDF GENERATOR CORE
# =========================
def create_pdf(data, file_path):

    doc = SimpleDocTemplate(file_path)
    styles = getSampleStyleSheet()

    content = []

    # Title
    content.append(Paragraph("🌾 Smart Agriculture Disease Report", styles["Title"]))
    content.append(Spacer(1, 12))

    # Disease Info
    content.append(Paragraph(f"🌿 Disease Detected: {data['disease']}", styles["Heading2"]))
    content.append(Paragraph(f"📊 Confidence: {round(data['confidence'], 2)}%", styles["Normal"]))
    content.append(Spacer(1, 12))

    # Advisory
    content.append(Paragraph("🌱 Advisory", styles["Heading2"]))
    content.append(Paragraph(translate(data["advice"], data["language"]), styles["Normal"]))
    content.append(Spacer(1, 10))

    # Medicine
    content.append(Paragraph("💊 Medicine", styles["Heading2"]))
    content.append(Paragraph(translate(data["medicine"], data["language"]), styles["Normal"]))
    content.append(Spacer(1, 10))

    # Fertilizer
    if data.get("fertilizer"):
        content.append(Paragraph("🌿 Fertilizer", styles["Heading2"]))
        content.append(Paragraph(translate(data["fertilizer"], data["language"]), styles["Normal"]))
        content.append(Spacer(1, 10))

    # Soil & Root Analysis
    if data.get("soil") or data.get("root_health"):
        content.append(Paragraph("🌱 Soil & Root Analysis", styles["Heading2"]))
        content.append(Paragraph(f"🪴 Soil: {data.get('soil','N/A')}", styles["Normal"]))
        content.append(Paragraph(f"🌳 Root: {data.get('root_health','N/A')}", styles["Normal"]))
        content.append(Spacer(1, 10))

    # Footer
    content.append(Spacer(1, 20))
    content.append(Paragraph("🤖 Generated by AgriFuture AI System", styles["Italic"]))

    doc.build(content)


# =========================
# 🚀 GENERATE REPORT API
# =========================
@router.post("/generate-report")
def generate_report(req: ReportRequest, user: dict = Depends(verify_token)):

    report_id = str(uuid.uuid4())
    file_name = f"{report_id}.pdf"
    file_path = os.path.join(REPORT_DIR, file_name)

    try:
        create_pdf(req.dict(), file_path)

        return {
            "status": "success",
            "report_id": report_id,
            "download_url": f"/api/report/download/{report_id}"
        }

    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }


# =========================
# 📥 DOWNLOAD API
# =========================
@router.get("/download/{report_id}")
def download_report(report_id: str):

    file_path = os.path.join(REPORT_DIR, f"{report_id}.pdf")

    if not os.path.exists(file_path):
        return {
            "status": "error",
            "message": "Report not found"
        }

    return FileResponse(
        path=file_path,
        media_type="application/pdf",
        filename="Agri_Disease_Report.pdf"
    )